added manifest & logo to zip
massalabs/thyra-node-manager-plugin pull request #46
Opened 2023-04-18 12:42 UTC by Pierregvx

2023-04-18 15:09 UTC, 0xMazout approved these changes
LGTM , Tested and Approved

2023-04-18 18:00 UTC, peterjah commented on .github/workflows/build.yml
> +      ZIP_NAME: thyra-plugin-node-manager_${{ matrix.target }}-${{ matrix.arch }}.zip
maybe its not needed to create this one.
you can just use `$TARGET_NAME.zip` in "run" jobs or `${{ env.TARGET_NAME }}.zip` elsewhere

2023-04-18 18:00 UTC, peterjah commented on .github/workflows/build.yml
> +          path: ${{ env.ZIP_NAME }}
be aware you are changing the behaviour of the CI.
Because when you download job artifact from github, it creates a zip file with the artifact.
So here you will have a zip into a zip.
Maybe its bad or not.. I don't know !
if you want to keep the same you can use
```
        uses: actions/upload-artifact@v3
        with:
          name: thyra-plugin-node-manager_${{ matrix.target }}-${{ matrix.arch }}
          path: |
            $TARGET_NAME${{ matrix.ext }}
            manifest.json
            logo.svg
```

2023-04-18 21:14 UTC, Pierregvx commented on .github/workflows/build.yml
> +          path: ${{ env.ZIP_NAME }}
I had only one zip [in the test I did](https://github.com/massalabs/thyra-node-manager-plugin/actions/runs/4732438296), but it is true that this way is better :+1:

2023-04-19 07:29 UTC, mazmassa approved these changes
LGTM!

2023-04-19 07:30 UTC, peterjah requested changes

2023-04-19 07:30 UTC, peterjah commented on .github/workflows/build.yml
>          run: zip $TARGET_NAME.zip $TARGET_NAME${{ matrix.ext }}
Now your job artifacts will contains the logo and manifest. but the zip used for releases assets does not !!!
its to separate things who are not triggered at the same time
artifacts => at every commit push on main
release => manual triggering of release workflow
you can just add tho 2 files in the zip command:
`run: zip $TARGET_NAME.zip $TARGET_NAME${{ matrix.ext }} manifest.json logo.svg`

2023-04-19 09:27 UTC, peterjah approved these changes

2023-04-19 09:37 UTC, merged